### ISSUE TITLE
Epic 0.1

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/CSM-SET#23]
- [ ] environment.yml
- [ ] conda installable usgscam (which needs the csm)
- [ ] conda installable sensorutils bindings
- [ ] load the ISD v 0.1.2
- [ ] instantiate the sensor
- [ ] pass in a pixel location and get a number back (phase, emission, ra&dec)
- [ ] pass in a ground location and do the previous
- [ ] all in a jupyter notebook
